### PR TITLE
Feature/badgeCounter

### PR DESCRIPTION
**Pull request by Knight704**
Please take a look if generally the idea is okay. Also I don't know if you have any objections about using 3rd party libraries (that I used in this PR)

If everything is fine I'll prepare test coverage for code written so far

### CODE REVIEW

**Comment by rlepinski** [comment]
We try to avoid using 3rd party libraries in our core SDK, other than the ones that are basically required for typical Android development. I am not also not sure if it makes sense long term due to the direction Android is headed (notification dots).

The code looks good and I am sure several people will want to use it. You can accomplish this as a stand alone library without needed to build it directly into Urban Airship. The only hook you need from UA is to be notified when the message is received. You can accomplish this with an AirshipReceiver that your library can have added automatically. If you are interested in that route, I can help you get started.

**Comment by Knight704** [comment]
Ok, thank you for your reply.
Yes, I think I'd extract this into separate lib, mostly I need this in my projects, but would be great if it helps someone else. Actually I did already create repo and push the same code there as in this PR ([Repo here](https://github.com/Knight704/UrbanAirshipBadgeCounterAndroid)).

I hope I'll have some spare time next week to take a look how to better integrate into existing core code. I wanted this extension be useful both on android and react-native module. I'll head to extending broadcast receiver, but maybe find some other way to do that

**Comment by rlepinski** [comment]
@Knight704 You will have to manage your own way of getting an instance and configuring what key to look for, but here is the receiver code you need:
```
import android.content.Context;
import android.support.annotation.NonNull;

import com.urbanairship.AirshipReceiver;
import com.urbanairship.push.PushMessage;

public class BadgeAirshipReceiver extends AirshipReceiver {

    @Override
    protected void onPushReceived(@NonNull Context context, @NonNull PushMessage message, boolean notificationPosted) {
        super.onPushReceived(context, message, notificationPosted);

        BadgeManager.getInstance(context).onPushReceived(message);
    }
}
```

Manifest entry:
```
        <receiver
            android:name=".BadgeAirshipReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="com.urbanairship.push.RECEIVED"/>
                <category android:name="${applicationId}"/>
            </intent-filter>
        </receiver>
```

**Comment by Knight704** [comment]
@rlepinski, finally created [android lib](https://github.com/Knight704/UrbanAirshipBadgeCounterAndroid) and its [](react-native wrapper). Any suggestions appreciated

**Comment by ashley-figueira** [comment]
@rlepinski Is it possible to implement this behavior but only when we receive a message for the message centre? Is there like a Message Centre listener similar to the onPushReceived which i believe is only for push notifications.

**Pull request closed without merging**
